name: Example Workflow for Environment Files

on: 
  workflow_dispatch:
    inputs:
      choice_input:
        description: 'A choice input'
        required: true
        default: 'Option1'
        options:
          - allowed
          - notallowed
          - donothing

jobs:
  set_and_use_env_vars:
    runs-on: ubuntu-latest
    env:
      the_secret: "Mona is best"
    steps:
      - name: Set environment variables
        run: |
          echo "MY_ENV_VAR=firstgithub_env_variable01" >> "$GITHUB_ENV"
          echo "configFilename=second_vsBatchwebconfig" >> "$GITHUB_ENV"
          echo "configname=pathoffile" >> "$GITHUB_ENV"
          echo "My file location is $configname"
          bi=$(echo "$configname")
          echo $bi
          calledvar=${{ env.MY_ENV_VAR }}-${{ env.configname }}
          echo "$calledvar"

      - name: Use environment variables
        run: |
          echo "The value of the_secret is ${{ env.the_secret }}"
          echo "The value of configFilename is ${{ env.configFilename }}"
          the_secret="Mona is best"
          echo "$the_secret"
          calledvar=${{ env.MY_ENV_VAR }}-${{ env.configname }}-$the_secret
          echo $calledvar
          
                  

      - name: Check image
        run: |
         calledvar="${{ env.MY_ENV_VAR }}-${{ env.configname }}"
         check_image=$(echo "$calledvar" | grep "first" || true)
         echo "chec_image=$check_image" >> $GITHUB_ENV
         echo "$check_image"

      - name: Check image and set variable
        run: |
          calledvar="${{ env.MY_ENV_VAR }}-${{ env.configname }}"
          check_image=$(echo "$calledvar" | grep "first" || true)
          if [ -n "$check_image" ]; then
          echo "check_image=found" >> $GITHUB_ENV
          else
          echo "check_image=not_found" >> $GITHUB_ENV
          fi
          echo "The value of check_image is $check_image"

      - name: If check_image is found
        if: ${{ env.check_image == 'found' }}
        run: echo "The string 'first' was found in the variable."

      - name: If check_image is not found
        if: ${{ env.check_image == 'not_found' }}
        run: echo "The string 'first' was not found in the variable."

         


      - name: Option if allowed
        if: ${{ github.event.inputs.choice_input == 'allowed' }}
        run: |
         echo "Input action is allowed"
         echo "$chec_image"
         echo "${{env.chec_image}}"

      - name: Option if not allowed
        #if: ${{ github.event.inputs.choice_input == 'notallowed'}} && ${{ github.actor == 'sumit' || github.actor == 'amit' || github.actor == 'naveen'}} 
       # if: ${{ github.event.inputs.choice_input == 'notallowed' }}
        if: ${{ (github.event.inputs.choice_input == 'notallowed' && (github.actor == 'naveennn' || github.actor == 'amit' || github.actor == 'naveen')) }}
        run: echo "Input action is not allowed"

      - name: Do nothing
        if: ${{ github.event.inputs.choice_input == 'donothing' }}
        run: echo "Input action is do nothing"
